### ISSUE TITLE
Email should be the same as the username

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#38]
This is a much better user experience, one less thing to remember or generate. We can keep them as two columns in the backend just to avoid worrying about having to change that code.

**Comment by lilliputten** [comment]
@cmutel

~~Does it mean to use email as a primary key? Or to sync the `email` field to the `username` one forcibly?~~

I've made one more attempt to use a custom implementation of `UserProfile`, but it seems that those simple solutions don't work in the project: probably due to a few third-party auth-related libraries used here, which don't allow using different/non-standard models.

I'm going to try to find a way to sync `email` to `username`, make `email` required and unique (already have seen your links in the next issue), and hide `username` from forms, or smth like this.
